link=document.createElement('script');
link.src='http://rapport.myro.be/Include/studentTab.js?3';
document.getElementsByTagName('head')[0].appendChild(link);

link=document.createElement('script');
link.src='http://rapport.myro.be/Include/reportOptions.js';
document.getElementsByTagName('head')[0].appendChild(link);

link=document.createElement('script');
link.src='http://rapport.myro.be/Include/jquery-1.6.2.min.js';
document.getElementsByTagName('head')[0].appendChild(link)
